name: tennis_stat
description: Tennis Stat app for friendly games.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.1.0
  cupertino_icons: ^1.0.0
  innim_lint: ^0.1.0
  innim_lib:
    git:
      url: http://git.innim.ru:1414/flutter/plugins/
      path: packages/innim_lib
      ref: innim_lib/0.2
  innim_ui:
    git:
      url: http://git.innim.ru:1414/flutter/plugins/
      path: packages/ui/innim_ui
      ref: innim_ui/0.3
  get_it: ^5.0.1
  multiple_localization: ^0.1.0+5
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9
  build_runner: ^1.10.0
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true

alex:
  l10n:
    xml_output_dir: lib/application/l10n/google_play